"""2 revision

Revision ID: dbe64e5b81c8
Revises: 72cb8946412f
Create Date: 2025-04-10 19:38:35.110319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe64e5b81c8'
down_revision: Union[str, None] = '72cb8946412f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
